In [4]:
import pandas as pd
df=pd.read_excel("ESD.xlsx")
#print(data)
df.loc[(df["Bonus %"] == 0), "GetsBonus"] ="no bonus"
df.loc[(df["Bonus %"] > 0, "getBonus")] = "bonus"
print(df.head(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT
1  E04105    Theodore Dinh       Technical Architect          IT
2  E02572     Luna Sanders                  Director     Finance
3  E02832  Penelope Jordan  Computer Systems Manager          IT
4  E01639        Austin Vo               Sr. Analyst     Finance
5  E00644     Joshua Gupta    Account Representative       Sales
6  E01550      Ruby Barnes                   Manager          IT
7  E04332      Luke Martin                   Analyst     Finance
8  E04533    Easton Bailey                   Manager  Accounting
9  E03838  Madeline Walker               Sr. Analyst     Finance

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604
1           Manufacturing    Male      Asian   59 1997-11-29          99975
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913
4           Manufacturing    Male      Asian   55 1995-11-20          95409
5               Corporate    Male      Asian   57 2017-01-24          50994
6               Corporate  Female  Caucasian   27 2020-07-01         119746
7           Manufacturing    Male      Black   25 2020-05-16          41336
8           Manufacturing    Male  Caucasian   29 2019-01-25         113527
9     Speciality Products  Female  Caucasian   34 2018-06-13          77203

   Bonus %        Country       City  Exit Date GetsBonus getBonus
0     0.15  United States    Seattle 2021-10-16       NaN    bonus
1     0.00          China  Chongqing        NaT  no bonus      NaN
2     0.20  United States    Chicago        NaT       NaN    bonus
3     0.07  United States    Chicago        NaT       NaN    bonus
4     0.00  United States    Phoenix        NaT  no bonus      NaN
5     0.00          China  Chongqing        NaT  no bonus      NaN
6     0.10  United States    Phoenix        NaT       NaN    bonus
7     0.00  United States      Miami 2021-05-20  no bonus      NaN
8     0.06  United States     Austin        NaT       NaN    bonus
9     0.00  United States    Chicago        NaT  no bonus      NaN

In [10]:
data = pd.read_excel("banking Data.xlsx")
print(data)

data["Full Name"] = data["First Name"].str.upper() + " " + data["Last Name"]
print(data)

     Client ID              Name  Age     Sex  Location ID Joined Bank  \
0     PKR81288     Raymond Mills   24    Male        34324  2019-05-06
1     PKR65833     Julia Spencer   23    Male        42205  2001-12-10
2     PKR47499    Stephen Murray   27  Female         7314  2010-01-25
3     PKR72498    Virginia Garza   40    Male        34594  1993-03-28
4     PKR60181   Melissa Sanders   46  Female        41269  2012-07-20
...        ...               ...  ...     ...          ...         ...
2995  PKR66827         Earl Hall   82  Female         8760  2014-10-09
2996  PKR40556  Billy Williamson   44  Female        32837  2009-02-05
2997  PKR72414      Victor Black   70  Female        36088  2009-12-29
2998  PKR46652       Andrew Ford   56  Female        24871  2006-02-13
2999  PKR40216        Amy Nguyen   79  Female        38518  2005-12-08

          Banking Contact Nationality                     Occupation  \
0          Anthony Torres    American           Safety Technician IV
1        Jonathan Hawkins     African            Software Consultant
2           Anthony Berry    European             Help Desk Operator
3              Steve Diaz    American                   Geologist II
4              Shawn Long    American            Assistant Professor
...                   ...         ...                            ...
2995       Joshua Bennett    American       Accounting Assistant III
2996          Dennis Ruiz    European                      Paralegal
2997          Joshua Ryan    American                Statistician IV
2998  Nicholas Cunningham    European  Human Resources Assistant III
2999           Joe Hanson    American            Biostatistician III

     Investment Advisor  ... Amount of Credit Cards Credit Card Balance  \
0           Victor Dean  ...                      1            484.5440
1         Jeremy Porter  ...                      1           2256.8777
2         Ernest Knight  ...                      2           4568.7438
3             Eric Shaw  ...                      2           4205.0010
4             Kevin Kim  ...                      1           3779.4880
...                 ...  ...                    ...                 ...
2995     Daniel Carroll  ...                      1            649.8540
2996     Peter Castillo  ...                      1           1639.0350
2997      Steve Sanchez  ...                      1           2352.8448
2998       Juan Ramirez  ...                      2           3578.6088
2999     Peter Castillo  ...                      1           1494.6876

        Bank Loans  Bank Deposits  Checking Accounts  Saving Accounts  \
0     7.762429e+05   1.485829e+06       6.036179e+05    607332.455240
1     1.270615e+06   6.414828e+05       2.295214e+05    344635.157402
2     1.052716e+06   1.033402e+06       6.526747e+05    203054.348179
3     1.211951e+05   1.048157e+06       1.048157e+06    234685.019326
4     1.048302e+06   4.877825e+05       4.466442e+05    128351.452320
...            ...            ...                ...              ...
2995  2.239351e+05   1.089957e+06       5.328679e+05    657849.619325
2996  5.959020e+05   1.368913e+05       5.658174e+04     93195.608103
2997  8.804930e+05   2.148609e+05       1.587261e+05     35539.152952
2998  2.686250e+05   7.426302e+05       4.046383e+05     56411.334112
2999  2.856407e+05   6.561766e+04       7.776908e+04     32371.380536

      Foreign Currency Account  Business Lending  Properties Owned  \
0                   12249.9584      1.134475e+06                 1
1                   61162.3089      2.000526e+06                 1
2                   79071.7794      5.481376e+05                 1
3                   57513.6520      1.148402e+06                 0
4                   30012.1360      1.674412e+06                 0
...                        ...               ...               ...
2995                12947.3100      1.238860e+06                 1
2996                23205.6900      2.771711e+05                 1
2997                30291.8112      5.029472e+05                 2
2998                 6413.1444      1.538369e+06                 3
2999                 8992.3608      3.294125e+05                 1

      Risk Weighting
0                  2
1                  3
2                  3
3                  4
4                  3
...              ...
2995               3
2996               2
2997               2
2998               1
2999               1

[3000 rows x 25 columns]

KeyError: 'First Name'